######################################################################
# Automatically generated by qmake (3.0) tir. okt. 14 17:12:16 2014
######################################################################

TEMPLATE = app
TARGET = snapfuck
INCLUDEPATH += /usr/include/qt/QtCrypto/

LIBS += -lqca-qt5

QT+= widgets network

QMAKE_CXXFLAGS += -std=c++11



# Input
HEADERS += oaes_common.h oaes_lib.h oaes_config.h \
    testwidget.h
SOURCES += oaes_lib.c main.cpp \
    testwidget.cpp
