######################################################################
# Automatically generated by qmake (3.0) tir. okt. 14 17:12:16 2014
######################################################################

TEMPLATE = app
TARGET = snapfuck

QT+= widgets network

QMAKE_CXXFLAGS += -std=c++11



# Input
HEADERS += aes.h \
    testwidget.h
SOURCES += main.cpp testwidget.cpp aes.c
